Repository AY2021S2-CS2103-W17-4/tp, pull requests merged in 2021-03, with the labels that each got.

#25 Adapt Meeting to JSON and create MeetingList
  README.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/MeetingList.java
  src/main/java/seedu/address/model/ReadOnlyMeetingList.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High

#52 Add Show Command to display a client in a dedicated fragment
  src/main/java/seedu/iscam/logic/Logic.java
  src/main/java/seedu/iscam/logic/LogicManager.java
  src/main/java/seedu/iscam/logic/commands/ShowCommand.java
  src/main/java/seedu/iscam/logic/parser/ClientBookParser.java
  src/main/java/seedu/iscam/logic/parser/exceptions/ShowCommandParser.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/ObservableClient.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/java/seedu/iscam/ui/MainWindow.java
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ShowCommandTest.java
Labels: priority.High, type.Story

#53 Integrate the functionality of Meeting commands
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/iscam/MainApp.java
  src/main/java/seedu/iscam/commons/core/Messages.java
  src/main/java/seedu/iscam/commons/util/StringUtil.java
  src/main/java/seedu/iscam/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/DoneMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/FindMeetingsCommand.java
  src/main/java/seedu/iscam/logic/commands/ListMeetingsCommand.java
  src/main/java/seedu/iscam/logic/commands/RelocateMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java
  src/main/java/seedu/iscam/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/CliSyntax.java
  src/main/java/seedu/iscam/logic/parser/ClientBookParser.java
  src/main/java/seedu/iscam/logic/parser/DoneMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/FindMeetingsCommandParser.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/RelocateMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/RescheduleMeetingCommandParser.java
  src/main/java/seedu/iscam/model/ClientBook.java
  src/main/java/seedu/iscam/model/MeetingBook.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/ReadOnlyClientBook.java
  src/main/java/seedu/iscam/model/ReadOnlyMeetingBook.java
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/main/java/seedu/iscam/model/meeting/Description.java
  src/main/java/seedu/iscam/model/meeting/Meeting.java
  src/main/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicate.java
  src/main/java/seedu/iscam/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/iscam/model/meeting/exceptions/MeetingConflictException.java
  src/main/java/seedu/iscam/model/meeting/exceptions/MeetingNotFoundException.java
  src/main/java/seedu/iscam/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/iscam/logic/LogicManagerTest.java
  src/test/java/seedu/iscam/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ClearCommandTest.java
  src/test/java/seedu/iscam/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/iscam/logic/commands/EditCommandTest.java
  src/test/java/seedu/iscam/logic/commands/FindCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ListCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ShowCommandTest.java
  src/test/java/seedu/iscam/model/ClientBookTest.java
  src/test/java/seedu/iscam/model/ModelManagerTest.java
  src/test/java/seedu/iscam/testutil/ClientBookBuilder.java
  src/test/java/seedu/iscam/testutil/MeetingBookBuilder.java
  src/test/java/seedu/iscam/testutil/MeetingBuilder.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: priority.High, type.Story

#55 Restructure Model Package and Update DG based on changes in Model
  docs/DeveloperGuide.md
  docs/diagrams/ClientBook.puml
  docs/diagrams/MeetingBook.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/FindCommand.java
  src/main/java/seedu/iscam/logic/commands/RelocateMeetingCommand.java
  src/main/java/seedu/iscam/logic/parser/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/EditCommandParser.java
  src/main/java/seedu/iscam/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/FindCommandParser.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/RelocateMeetingCommandParser.java
  src/main/java/seedu/iscam/model/client/Client.java
  src/main/java/seedu/iscam/model/commons/Location.java
  src/main/java/seedu/iscam/model/commons/Name.java
  src/main/java/seedu/iscam/model/commons/NameContainsKeywordsPredicate.java
  src/main/java/seedu/iscam/model/commons/Tag.java
  src/main/java/seedu/iscam/model/meeting/Meeting.java
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
  src/main/java/seedu/iscam/storage/JsonAdaptedClient.java
  src/main/java/seedu/iscam/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/iscam/storage/JsonAdaptedTag.java
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
  src/test/java/seedu/iscam/logic/commands/FindCommandTest.java
  src/test/java/seedu/iscam/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/ClientBookParserTest.java
  src/test/java/seedu/iscam/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/ParserUtilTest.java
  src/test/java/seedu/iscam/model/ModelManagerTest.java
  src/test/java/seedu/iscam/model/client/LocationTest.java
  src/test/java/seedu/iscam/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/iscam/model/client/NameTest.java
  src/test/java/seedu/iscam/model/tag/TagTest.java
  src/test/java/seedu/iscam/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/iscam/testutil/ClientBuilder.java
  src/test/java/seedu/iscam/testutil/ClientUtil.java
  src/test/java/seedu/iscam/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/iscam/testutil/MeetingBuilder.java
Labels: priority.Medium, type.Task

#58 V1.3 meeting list UI #2
  docs/DeveloperGuide.md
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/ui/MeetingCard.java
  src/main/resources/view/ClientCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MeetingCard.fxml
Labels: priority.Medium, type.Story

#61 Add meeting storage functionality
  src/main/java/seedu/iscam/MainApp.java
  src/main/java/seedu/iscam/logic/Logic.java
  src/main/java/seedu/iscam/logic/LogicManager.java
  src/main/java/seedu/iscam/logic/commands/ClearCommand.java
  src/main/java/seedu/iscam/logic/parser/MeetingBookParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/ClientBookParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/DeleteCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/FindCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/AddMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/DeleteMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/DoneMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/EditMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/FindMeetingsCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/RelocateMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/RescheduleMeetingCommandParser.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/iscam/model/UserPrefs.java
  src/main/java/seedu/iscam/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
  src/main/java/seedu/iscam/model/util/clientbook/ClientBook.java
  src/main/java/seedu/iscam/model/util/clientbook/ObservableClient.java
  src/main/java/seedu/iscam/model/util/clientbook/ReadOnlyClientBook.java
  src/main/java/seedu/iscam/model/util/meetingbook/MeetingBook.java
  src/main/java/seedu/iscam/model/util/meetingbook/ObservableMeeting.java
  src/main/java/seedu/iscam/model/util/meetingbook/ReadOnlyMeetingBook.java
  src/main/java/seedu/iscam/storage/ClientBookStorage.java
  src/main/java/seedu/iscam/storage/JsonClientBookStorage.java
  src/main/java/seedu/iscam/storage/JsonMeetingBookStorage.java
  src/main/java/seedu/iscam/storage/JsonSerializableClientBook.java
  src/main/java/seedu/iscam/storage/JsonSerializableMeetingBook.java
  src/main/java/seedu/iscam/storage/MeetingBookStorage.java
  src/main/java/seedu/iscam/storage/Storage.java
  src/main/java/seedu/iscam/storage/StorageManager.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/iscam/logic/LogicManagerTest.java
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ClearCommandTest.java
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
  src/test/java/seedu/iscam/logic/commands/EditCommandTest.java
  src/test/java/seedu/iscam/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/ClientBookParserTest.java
  src/test/java/seedu/iscam/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/iscam/model/ClientBookTest.java
  src/test/java/seedu/iscam/model/ModelManagerTest.java
  src/test/java/seedu/iscam/storage/JsonClientBookStorageTest.java
  src/test/java/seedu/iscam/storage/JsonSerializableClientBookTest.java
  src/test/java/seedu/iscam/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/iscam/storage/StorageManagerTest.java
  src/test/java/seedu/iscam/testutil/ClientBookBuilder.java
  src/test/java/seedu/iscam/testutil/MeetingBookBuilder.java
  src/test/java/seedu/iscam/testutil/TypicalClients.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: type.Task

#62 Remove remark
  bin/main/view/ClientListCard.fxml
  src/main/java/seedu/iscam/logic/parser/CliSyntax.java
  src/main/java/seedu/iscam/ui/ClientCard.java
  src/main/resources/view/ClientDetailFragment.fxml
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
Labels: priority.Medium, type.Bug

#65 Enable assertions and update window's title
  bin/main/view/MainWindow.fxml
  build.gradle
  src/main/java/seedu/iscam/model/MeetingList.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#66 Making insurance plan optional for add and edit commands
  src/main/java/seedu/iscam/logic/parser/clientcommands/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/model/client/Client.java
Labels: priority.Medium, type.Task

#67 Add find plan command
  src/main/java/seedu/iscam/logic/commands/AddCommand.java
  src/main/java/seedu/iscam/logic/commands/FindPlansCommand.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/ClientBookParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/FindPlansCommandParser.java
  src/main/java/seedu/iscam/model/client/PlanContainsKeywordsPredicate.java
Labels: priority.Medium, type.Enhancement

#69 Client details command
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/ShowCommand.java
  src/main/java/seedu/iscam/logic/parser/ShowCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/ClientBookParser.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/java/seedu/iscam/ui/MainWindow.java
  src/main/java/seedu/iscam/ui/MeetingListPanel.java
  src/main/resources/images/person_icon.png
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium, type.Story

#72 Added ability to add and view client images in ClientDetailsFragment
  src/main/java/seedu/iscam/logic/commands/AddCommand.java
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/parser/CliSyntax.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/model/client/Client.java
  src/main/java/seedu/iscam/model/client/Image.java
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
  src/main/java/seedu/iscam/storage/JsonAdaptedClient.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/resources/view/ClientDetailFragment.fxml
  src/test/data/JsonSerializableClientBookTest/duplicateClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/typicalClientsClientBook.json
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
  src/test/java/seedu/iscam/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/iscam/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/iscam/testutil/ClientBuilder.java
  src/test/java/seedu/iscam/testutil/ClientUtil.java
  src/test/java/seedu/iscam/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/iscam/testutil/TypicalClients.java
Labels: priority.Medium, type.Story

#73 Add meeting commands to UG / Update clear command to clear meetings
  docs/UserGuide.md
  docs/images/findmeetResult.png
  src/main/java/seedu/iscam/logic/commands/ClearCommand.java
  src/test/java/seedu/iscam/logic/commands/ClearCommandTest.java
Labels: priority.Medium, type.Task

#75 Added checks for illegal input in clientbook.json if imageRes is missing
  src/main/java/seedu/iscam/storage/JsonAdaptedClient.java
Labels: severity.Medium, type.Bug

#81 Correct index page and built .jar name
  build.gradle
  docs/images/ActualUi.png
  docs/index.md
  src/main/java/seedu/iscam/ui/HelpWindow.java
Labels: priority.High, type.Task
