Repository AY2021S2-CS2103-W17-4/tp, pull requests merged in 2021-04, with the labels that each got.

#83 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/show7.png
  src/main/java/seedu/iscam/logic/commands/AddCommand.java
  src/main/java/seedu/iscam/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/FindPlansCommand.java
Labels: priority.High, type.Task

#82 Fix command message
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/model/client/InsurancePlan.java
Labels: type.Bug

#84 Fix the saving of meeting's isDone field and Update help message screenshot for UG
  docs/images/helpMessage.png
  src/main/java/seedu/iscam/storage/JsonAdaptedMeeting.java
Labels: severity.High, type.Bug

#85 Updated storage UG, DG and added some MeetingBookStorage test cases
  docs/DeveloperGuide.md
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/iscam/model/meeting/Description.java
  src/main/java/seedu/iscam/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/iscam/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/iscam/storage/JsonMeetingBookStorageTest.java
  src/test/java/seedu/iscam/storage/JsonSerializableMeetingBookTest.java
  src/test/java/seedu/iscam/storage/StorageManagerTest.java
Labels: priority.Medium

#89 Status bar missing
  src/main/java/seedu/iscam/logic/commands/ShowCommand.java
  src/main/resources/view/ClientDetailFragment.fxml
Labels: severity.Low, type.Bug, type.Enhancement

#93 Finalise 1.3 version number
  src/main/java/seedu/iscam/MainApp.java
Labels: priority.High

#91 Add Image into Client package of Model's UML diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: priority.High, type.Task

#174 Package client and meeting files in Storage package into child packages
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/members/frisciliasultan.png
  docs/images/members/jodylorah.png
  docs/images/members/juzzanoob.png
  docs/images/members/tomashiwa.png
  docs/images/members/zaiah0505.png
  docs/images/members/zoeykobe.png
  src/main/java/seedu/iscam/MainApp.java
  src/main/java/seedu/iscam/logic/events/ClearCommandEvent.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/meeting/MeetingList.java
  src/main/java/seedu/iscam/model/meeting/ReadOnlyMeetingList.java
  src/main/java/seedu/iscam/model/user/ReadOnlyUserPrefs.java
  src/main/java/seedu/iscam/model/user/UserPrefs.java
  src/main/java/seedu/iscam/storage/Storage.java
  src/main/java/seedu/iscam/storage/StorageManager.java
  src/main/java/seedu/iscam/storage/client/ClientBookStorage.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClient.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClientTag.java
  src/main/java/seedu/iscam/storage/client/JsonClientBookStorage.java
  src/main/java/seedu/iscam/storage/client/JsonSerializableClientBook.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTag.java
  src/main/java/seedu/iscam/storage/meeting/JsonMeetingBookStorage.java
  src/main/java/seedu/iscam/storage/meeting/JsonSerializableMeetingBook.java
  src/main/java/seedu/iscam/storage/meeting/MeetingBookStorage.java
  src/main/java/seedu/iscam/storage/user/JsonUserPrefsStorage.java
  src/main/java/seedu/iscam/storage/user/UserPrefsStorage.java
  src/test/java/seedu/iscam/logic/LogicManagerTest.java
  src/test/java/seedu/iscam/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ClearCommandTest.java
  src/test/java/seedu/iscam/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/iscam/logic/commands/EditCommandTest.java
  src/test/java/seedu/iscam/logic/commands/FindCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ListCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ShowCommandTest.java
  src/test/java/seedu/iscam/model/ModelManagerTest.java
  src/test/java/seedu/iscam/model/UserPrefsTest.java
  src/test/java/seedu/iscam/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/iscam/storage/StorageManagerTest.java
  src/test/java/seedu/iscam/storage/client/JsonAdaptedClientTest.java
  src/test/java/seedu/iscam/storage/client/JsonClientBookStorageTest.java
  src/test/java/seedu/iscam/storage/client/JsonSerializableClientBookTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonMeetingBookStorageTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonSerializableMeetingBookTest.java
Labels: priority.Medium, type.Task

#175 Correct the feedback message that is displayed when editMeet makes no changes
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
Labels: severity.Medium, type.Enhancement

#172 Corrects UG to indicate that findmeet search by keywords via AND instead of OR
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#171 Adds spacing to correct feedback message for EditMeeting
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
Labels: severity.Medium, type.Bug

#173 Fixes the bug where clientbook and meetingbook get wiped after loading an expired meeting
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
Labels: severity.High, type.Bug

#179 Fix a bug where a completed meeting can become incomplete via editmeet command
  src/main/java/seedu/iscam/logic/commands/DoneMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/RelocateMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java
  src/main/java/seedu/iscam/logic/parser/CliSyntax.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/EditMeetingCommandParser.java
  src/main/java/seedu/iscam/model/meeting/CompletionStatus.java
  src/main/java/seedu/iscam/model/meeting/Meeting.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/iscam/ui/MeetingCard.java
  src/main/resources/view/MeetingCard.fxml
  src/test/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTest.java
  src/test/java/seedu/iscam/testutil/MeetingBuilder.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: priority.High, type.Bug

#176 Update clear success message to make it clearer
  src/main/java/seedu/iscam/logic/commands/ClearCommand.java
Labels: severity.VeryLow

#186 Add checks for date-time conflict with existing meetings when editing or rescheduling a meeting
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/util/meetingbook/MeetingBook.java
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
Labels: severity.High, type.Bug

#188 Prevent relocation of a completed meeting
  src/main/java/seedu/iscam/logic/commands/RelocateMeetingCommand.java
Labels: severity.Medium, type.Bug

#189 Fix all error message bugs
  src/main/java/seedu/iscam/commons/core/Messages.java
  src/main/java/seedu/iscam/commons/util/StringUtil.java
  src/main/java/seedu/iscam/logic/LogicManager.java
  src/main/java/seedu/iscam/logic/commands/DeleteCommand.java
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/DeleteCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/logic/parser/exceptions/ParseIndexException.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/DeleteMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/EditMeetingCommandParser.java
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/test/java/seedu/iscam/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/EditCommandParserTest.java
Labels: severity.Medium, type.Bug

#190 Add the ability to find meetings by status
  src/main/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicate.java
Labels: severity.Medium, type.Bug

#192 Address unclear error message for DateTime
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
  src/test/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTest.java
Labels: severity.Low, type.Bug

#187 Fix regression in editmeet caused by introducing date-time conflict check with existing meetings
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/util/meetingbook/MeetingBook.java
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
Labels: severity.High, type.Bug

#197 Sorting Meetings with uncompleted meetings at the top
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/meeting/UniqueMeetingList.java
Labels: severity.Medium, type.Enhancement

#196 Findmeet can now search by day of week
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/main/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicate.java
Labels: severity.Low, type.Bug

#194 Restrict editing and rescheduling of meeting to uncompleted meetings
  docs/UserGuide.md
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java
Labels: severity.Medium, type.Bug

#200 Closed issues listed in module forum
  docs/_sass/minima/_base.scss
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/iscam/logic/commands/AddCommand.java
  src/main/java/seedu/iscam/logic/commands/ExitCommand.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/model/client/Client.java
  src/main/java/seedu/iscam/model/client/Email.java
  src/main/java/seedu/iscam/model/client/InsurancePlan.java
  src/main/java/seedu/iscam/model/client/Phone.java
  src/main/java/seedu/iscam/model/commons/Location.java
  src/main/java/seedu/iscam/model/commons/Name.java
  src/main/java/seedu/iscam/model/commons/Tag.java
  src/main/java/seedu/iscam/model/util/clientbook/ClientBook.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClient.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClientTag.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTag.java
  src/test/data/JsonClientBookStorageTest/invalidAndValidClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/invalidClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/typicalClientsClientBook.json
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
  src/test/java/seedu/iscam/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/ParserUtilTest.java
  src/test/java/seedu/iscam/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/iscam/model/client/PhoneTest.java
  src/test/java/seedu/iscam/storage/client/JsonAdaptedClientTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonAdaptedMeetingTest.java
  src/test/java/seedu/iscam/testutil/TypicalClients.java
Labels: type.Bug

#195 Correct DateTime to display error message when invalid date is given
  src/main/java/seedu/iscam/model/meeting/DateTime.java
Labels: severity.Low, type.Bug

#202 Add test cases for MeetingBookStorage
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java
  src/test/data/JsonClientBookStorageTest/invalidClientClientBook.json
  src/test/data/JsonMeetingBookStorageTest/invalidAndValidMeetingMeetingBook.json
  src/test/data/JsonMeetingBookStorageTest/invalidMeetingMeetingBook.json
  src/test/data/JsonMeetingBookStorageTest/notJsonFormatMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/duplicateMeetingMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/invalidMeetingMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/typicalMeetingsMeetingBook.json
  src/test/java/seedu/iscam/storage/StorageManagerTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonMeetingBookStorageTest.java
  src/test/java/seedu/iscam/storage/meeting/JsonSerializableMeetingBookTest.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: priority.High, type.Task

#206 Add testing for Meeting, its parameter classes and its model classes
  src/main/java/seedu/iscam/model/client/UniqueClientList.java
  src/main/java/seedu/iscam/model/meeting/DateTime.java
  src/main/java/seedu/iscam/model/meeting/Description.java
  src/main/java/seedu/iscam/model/meeting/Meeting.java
  src/main/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicate.java
  src/main/java/seedu/iscam/model/meeting/MeetingList.java
  src/main/java/seedu/iscam/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/iscam/model/ClientBookTest.java
  src/test/java/seedu/iscam/model/MeetingBookTest.java
  src/test/java/seedu/iscam/model/meeting/CompletionStatusTest.java
  src/test/java/seedu/iscam/model/meeting/DateTimeTest.java
  src/test/java/seedu/iscam/model/meeting/DescriptionTest.java
  src/test/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicateTest.java
  src/test/java/seedu/iscam/model/meeting/MeetingTest.java
  src/test/java/seedu/iscam/model/meeting/UniqueMeetingListTest.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: severity.High, type.Task

#208 Split screen
  src/main/java/seedu/iscam/logic/Logic.java
  src/main/java/seedu/iscam/logic/LogicManager.java
  src/main/java/seedu/iscam/logic/commands/ListCommand.java
  src/main/java/seedu/iscam/logic/commands/ListMeetingsCommand.java
  src/main/java/seedu/iscam/logic/commands/ShowCommand.java
  src/main/java/seedu/iscam/model/Model.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/ui/MainWindow.java
  src/main/resources/view/ClientCard.fxml
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingCard.fxml
  src/test/java/seedu/iscam/logic/commands/AddCommandTest.java
Labels: priority.High, severity.High, type.Bug

#209 Update images in StorageClassDiagram and LogicClassDiagram to include updated storage
  docs/DeveloperGuide.md
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.Task

#207 Update UG based on changes made from debugging Meeting
  docs/UserGuide.md
  src/main/java/seedu/iscam/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/iscam/logic/commands/FindMeetingsCommand.java
  src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java
Labels: priority.High, type.Task

#210 Done PPP
  docs/team/jodylorah.md
Labels: priority.High, type.Task

#212 Image attribution
  docs/DeveloperGuide.md
Labels: priority.High, severity.High, type.Bug

#211 Show and delete
  src/main/java/seedu/iscam/logic/commands/DeleteCommand.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.High, type.Bug

#213 Configured both Edit and EditMeet commands to return the same output …
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/EditMeetingCommand.java
  src/test/java/seedu/iscam/logic/commands/EditCommandTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#219 Fixes the findmeet bug when using complete and incomplete with other keywords
  src/main/java/seedu/iscam/model/meeting/MeetingContainsKeywordsPredicate.java
Labels: severity.High, type.Bug

#220 Shaun insurance list
  docs/UserGuide.md
  docs/team/jodylorah.md
  src/main/java/seedu/iscam/commons/util/StringUtil.java
  src/main/java/seedu/iscam/logic/CommandHistory.java
  src/main/java/seedu/iscam/logic/commands/AddCommand.java
  src/main/java/seedu/iscam/logic/commands/DeleteCommand.java
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/UndoableCommand.java
  src/main/java/seedu/iscam/logic/events/AddEventFactory.java
  src/main/java/seedu/iscam/logic/events/DeleteClientEvent.java
  src/main/java/seedu/iscam/logic/events/DeleteEventFactory.java
  src/main/java/seedu/iscam/logic/events/EditClientEvent.java
  src/main/java/seedu/iscam/logic/events/EditEventFactory.java
  src/main/java/seedu/iscam/logic/events/Event.java
  src/main/java/seedu/iscam/logic/events/EventFactory.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/DeleteCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/model/client/Client.java
  src/main/java/seedu/iscam/model/client/InsurancePlan.java
  src/main/java/seedu/iscam/model/client/PlanContainsKeywordsPredicate.java
  src/main/java/seedu/iscam/model/meeting/CompletionStatus.java
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClient.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClientPlan.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/java/seedu/iscam/ui/MainWindow.java
  src/main/java/seedu/iscam/ui/PlanCard.java
  src/main/java/seedu/iscam/ui/PlanListPanel.java
  src/main/resources/view/ClientCard.fxml
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingCard.fxml
  src/main/resources/view/PlanCard.fxml
  src/main/resources/view/PlanListPanel.fxml
  src/test/data/JsonSerializableClientBookTest/duplicateClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/typicalClientsClientBook.json
  src/test/java/seedu/iscam/storage/client/JsonAdaptedClientTest.java
  src/test/java/seedu/iscam/testutil/ClientBuilder.java
  src/test/java/seedu/iscam/testutil/ClientUtil.java
  src/test/java/seedu/iscam/testutil/EditClientDescriptorBuilder.java
Labels: severity.Medium, type.Enhancement

#214 Insurance plan modification
  docs/UserGuide.md
  docs/team/jodylorah.md
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/parser/ParserUtil.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/AddCommandParser.java
  src/main/java/seedu/iscam/logic/parser/clientcommands/EditCommandParser.java
  src/main/java/seedu/iscam/model/client/Client.java
  src/main/java/seedu/iscam/model/client/InsurancePlan.java
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClient.java
  src/main/java/seedu/iscam/storage/client/JsonAdaptedClientPlan.java
  src/test/java/seedu/iscam/storage/client/JsonAdaptedClientTest.java
Labels: priority.Medium

#217 Correct english errors
  docs/UserGuide.md
Labels: priority.High

#221 UI enhancements
  src/main/resources/view/ClientDetailFragment.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: severity.VeryLow, type.Enhancement

#242 Add meeting integration test
  src/test/java/seedu/iscam/logic/commands/AddMeetingCommandIntegrationTest.java
  src/test/java/seedu/iscam/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/FindPlansCommandParserTest.java
Labels: priority.High, type.Task

#247 Corrects gradle's JavaFX version to align with FXML files
  build.gradle
Labels: severity.Low, type.Bug

#249 Corrects sample data json to work with client list
  src/main/java/seedu/iscam/model/util/SampleDataUtil.java
Labels: severity.Low, type.Enhancement

#248 Removes the meeting list from success message for listmeet and findmeet
  src/main/java/seedu/iscam/logic/commands/FindMeetingsCommand.java
  src/main/java/seedu/iscam/logic/commands/ListMeetingsCommand.java
  src/test/java/seedu/iscam/logic/commands/FindMeetingsCommandTest.java
  src/test/java/seedu/iscam/logic/commands/ListMeetingsCommandTest.java
Labels: severity.Medium, type.Enhancement

#251 PPP and Remove "..."
  docs/team/zoeykobe.md
  src/main/java/seedu/iscam/logic/commands/EditCommand.java
  src/main/java/seedu/iscam/logic/commands/FindCommand.java
  src/main/java/seedu/iscam/logic/commands/FindPlansCommand.java
Labels: priority.High, type.Task

#253 Remove Undo/Redo from DG
  docs/DeveloperGuide.md
Labels: priority.High

#254 About Us page
  docs/AboutUs.md
  docs/team/jodylorah.md
Labels: priority.Medium

#252 Add PPP
  docs/team/tomashiwa.md
Labels: priority.High, type.Task

#250 Parser tests
  src/main/java/seedu/iscam/logic/parser/ShowCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/AddMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/DoneMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/RelocateMeetingCommandParser.java
  src/main/java/seedu/iscam/logic/parser/meetingcommands/RescheduleMeetingCommandParser.java
  src/test/java/seedu/iscam/logic/commands/CommandTestUtil.java
  src/test/java/seedu/iscam/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/AddMeetingCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/DoneMeetingCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/EditMeetingCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/FindMeetingsCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/RelocateMeetingCommandParserTest.java
  src/test/java/seedu/iscam/logic/parser/meetingcommands/RescheduleMeetingCommandParserTest.java
  src/test/java/seedu/iscam/testutil/TypicalMeetings.java
Labels: priority.High, type.Task

#255 Add Activity Diagrams for Client Commands in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddClientActivityDiagram.png
  docs/images/DeleteClientActivityDiagram.png
  docs/images/FindClientByNameActivityDiagram.png
Labels: priority.High

#256 Add Sequence Diagrams for Client commands to DG
  docs/DeveloperGuide.md
  docs/images/AddClientSequenceDiagram.png
  docs/images/DeleteClientSequenceDiagram.png
  docs/images/FindClientSequenceDiagram.png
Labels: priority.High

#258 Fix linking from AboutUs to PPP
  docs/AboutUs.md
Labels: type.Bug

#266 Effort section and Wrap Text of Date
  docs/DeveloperGuide.md
  src/main/java/seedu/iscam/ui/MeetingCard.java
Labels: priority.Medium, type.Task

#267 UI documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ShowCommandSequenceDiagram.png
  src/main/java/seedu/iscam/model/client/Image.java
Labels: priority.High, type.Task

#257 Removed separator in ClientDetailFragment when in tooltip mode and ed…
  src/main/java/seedu/iscam/logic/commands/DeleteCommand.java
  src/main/java/seedu/iscam/model/ModelManager.java
  src/main/java/seedu/iscam/model/util/clientbook/ObservableClient.java
  src/main/java/seedu/iscam/ui/ClientDetailFragment.java
  src/main/resources/view/ClientDetailFragment.fxml
  src/test/java/seedu/iscam/logic/commands/DeleteCommandTest.java
Labels: severity.Medium, type.Bug

#269 Made ClientDetailFragment refresh when clearCommand is called
  src/main/java/seedu/iscam/logic/commands/ClearCommand.java
Labels: severity.Medium, type.Bug

#271 Rectify UML diagram errors in DG
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
Labels: priority.High

#272 Add text stating tags for clients and meetings should not contain spaces
  docs/UserGuide.md
Labels: priority.Medium

#276 Updated the screenshots of deprecated diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: severity.High, type.Task

#278 Remove tutorial pages from DG
  docs/SettingUp.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: priority.Medium, type.Task

#270 README, Index Page and User Stories and Use Cases in DG
  README.md
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: type.Task

#288 Adds Manual Testing section for DG
  docs/DeveloperGuide.md
Labels: severity.High, type.Task

#286 Update screenshot for showCommand in UG
  docs/UserGuide.md
Labels: severity.High

#292 Fix issues in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiWithoutActiveClient.png
  docs/images/editmeetResult.png
  docs/images/findAlexDavidResult.png
Labels: severity.High
